version: '3.4'

services:

  productdb:
      image: mcr.microsoft.com/mssql/server:2022-latest
      container_name: productdb
      restart: always
      mem_limit: 4GB
      environment:
        SA_PASSWORD: "Qaz@123456!"
        ACCEPT_EULA: "Y"
        MSSQL_PID: "Enterprise"
        TZ: "Asia/Tehran"

  rdis:
    image: redis:latest
    container_name: rdis
    restart: always
    ports:
      - "6379:6379"

  productapi:
    image: productapi:v1.0.0
    build:
      context: .
      dockerfile: src/Services/Product/Product.API/Dockerfile
    container_name: productapi
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80;
      - TZ=Asia/Tehran
    ports:
      - "5001:80"
    depends_on:
      - productdb

  identityapi:
    image: identityapi:v1.0.0
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile
    container_name: identityapi
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80;
      - TZ=Asia/Tehran
    ports:
      - "5000:80"
    depends_on:
      - rdis

  apigetway:
    image: apigetway:v1.0.0
    build:
      context: .
      dockerfile: src/ApiGetway/ApiGateway/Dockerfile
    container_name: apigetway
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - TZ=Asia/Tehran
    depends_on:
      - productapi
      - identityapi
    ports:
      - "3000:80"
